import { createMuiTheme } from '@material-ui/core/styles';
import {red, pink, purple, deepPurple, indigo, blue, lightBlue, cyan, teal, green, lightGreen, lime, yellow, amber, orange, deepOrange } from '@material-ui/core/colors';



const DarkTheme = createMuiTheme({
    AppBar: {
        backgroundColor: '#2a4c5d',
    },
    typography: {
        fontSize: 12
    },
    palette: {
        type: 'dark',
        primary: {
            main: teal[500],
        },
        secondary: {
            main: pink[900],
        },
    },
});

/* Palette generated by Material Palette - materialpalette.com/blue-grey/cyan */
/*
.dark-primary-color    { background: #455A64; }
.default-primary-color { background: #607D8B; }
.light-primary-color   { background: #CFD8DC; }
.text-primary-color    { color: #F0F0F0; }
.accent-color          { background: #00BCD4; }
.primary-text-color    { color: #212121; }
.secondary-text-color  { color: #757575; }
.divider-color         { border-color: #BDBDBD; }
*/

const LightTheme = createMuiTheme({
    AppBar: {
        backgroundColor: '#527180',
    },
    typography: {
        fontSize: 12
    },    
    palette: {
        //type: 'light',
        primary: {
            main: deepOrange[500],
        },
        secondary: {
            main: deepOrange[400],
        },
        background: {
            default: "#455A64",
            paper: "#bcc7cc"
        },
        alternateTextColor: pink[900]
    },
});

export {DarkTheme, LightTheme};